spring:
  datasource:
    url: jdbc:mysql://localhost:3306/just4emailmsg?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikairi:
      minimum-idle: 5
      maximum-pool-size: 50
      max-lifetime: 600000
      idleTimeout: 600000
      allowPoolSuspension: true



mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9004
